[tools]
python = { version = "3.12.1", venv = ".venv" }
uv = { version = "0.4.7"}

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tasks.start]
run = "uvicorn --host 0.0.0.0 --port 8000 gitops_server.main:app --reload"

[tasks."install"]
run = ["uv sync --all-extras"]

[tasks."lint"]
run = ["uv run ruff check ."]

[tasks."format"]
run = ["uv run ruff format ."]

[tasks."test"]
run = ["uv run py.test"]

[tasks."mypy"]
run = ["uv run mypy ."]

[tasks."ci"]
depends = ["lint", "format", "test", "mypy"]

[tasks."helm:lint"]
run = "helm install --dry-run --debug -f charts/gitops/values.yaml debug charts/gitops"

[tasks.release]
description = "Bump release versions across all files"
run = "python release.py"

[tasks.start_otel]
run = ["""
OTEL_PYTHON_LOG_CORRELATION=true \
OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=True \
OTEL_LOGS_EXPORTER=none \
OTEL_METRICS_EXPORTER=none \
OTEL_TRACES_EXPORTER=console \
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317 \
OTEL_RESOURCE_ATTRIBUTES=server_name=gitops \
OTEL_SERVICE_NAME=gitops-test \
OTEL_EXPORTER_OTLP_TIMEOUT=1 \
uvicorn --host 0.0.0.0 --port 7000 gitops_server.main:app"""]

[tasks.build]
run = "uv build"