repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff
    args:
    - --fix
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff-format
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.14.1
  hooks:
  - id: commitizen
    stages:
    - commit-msg
