version: "3"
services:
  web:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./gitops_server:/app/gitops_server
    environment:
      - GITHUB_SECRET=secret
      - SLACK_TOKEN
      - GIT_CRYPT_KEY_FILE
