services:
  web:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./common:/app/common
      - ./gitops_server:/app/gitops_server
      - ./tests:/app/tests
    env_file:
      - secrets.env
