apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gitops-cert
spec:
  secretName: gitops-cert-key
  issuerRef:
    name: gitops-issuer
    kind: Issuer
  dnsNames:
  - gitops.{{ .Values.domain }}
