apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-deployment
  labels:
    app: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitops
      annotations:
        checksum/environment: {{ include (print $.Template.BasePath "/environment.yml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yml") . | sha256sum }}
    spec:
      containers:
      - name: gitops
        image: {{ .Values.image }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: gitops-environment
        env:
          - name: SLACK_URL
            valueFrom:
              secretKeyRef:
                name: gitops-secrets
                key: SLACK_URL
          - name: GITHUB_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitops-secrets
                key: GITHUB_OAUTH_TOKEN
          - name: GITHUB_WEBHOOK_KEY
            valueFrom:
              secretKeyRef:
                name: gitops-secrets
                key: GITHUB_WEBHOOK_KEY
        volumeMounts:
        - name: git-crypt-key
          mountPath: "/etc/gitops"
          readOnly: true
        - name: kube-config
          mountPath: "/root/.kube"
          readOnly: true
      volumes:
      - name: git-crypt-key
        secret:
          secretName: gitops-secrets
          items:
          - key: GIT_CRYPT_KEY
            path: git_crypt_key
      - name: kube-config
        secret:
          secretName: gitops-secrets
          items:
          - key: KUBE_CONFIG
            path: config
      restartPolicy: Always
