# TODO: Anonymise this.
SAMPLE_GITHUB_PAYLOAD = {
    "ref": "refs/heads/master",
    "before": "78e218176a9d5c8b5b1e0323d30e230066f017fd",
    "after": "2aa726ef074f0e306578367db2c6fc4d5f571952",
    "created": False,
    "deleted": False,
    "forced": False,
    "base_ref": None,
    "compare": "https://github.com/uptick/uptick-cluster/compare/78e218176a9d...2aa726ef074f",
    "commits": [
        {
            "id": "2aa726ef074f0e306578367db2c6fc4d5f571952",
            "tree_id": "eb1149b491d9e0e6b5cdb250af9d98e36a2b7090",
            "distinct": True,
            "message": "Bump arafire-sandbox.",
            "timestamp": "2019-07-18T15:07:37+10:00",
            "url": "https://github.com/uptick/uptick-cluster/commit/2aa726ef074f0e306578367db2c6fc4d5f571952",
            "author": {
                "name": "Jarek Glowacki",
                "email": "jarekwg@gmail.com",
                "username": "jarekwg"
            },
            "committer": {
                "name": "Jarek Glowacki",
                "email": "jarekwg@gmail.com",
                "username": "jarekwg"
            },
            "added": [],
            "removed": [],
            "modified": ["apps/arafire-sandbox/deployment.yml"]
        }
    ],
    "head_commit": {
        "id": "2aa726ef074f0e306578367db2c6fc4d5f571952",
        "tree_id": "eb1149b491d9e0e6b5cdb250af9d98e36a2b7090",
        "distinct": True,
        "message": "Bump arafire-sandbox.",
        "timestamp": "2019-07-18T15:07:37+10:00",
        "url": "https://github.com/uptick/uptick-cluster/commit/2aa726ef074f0e306578367db2c6fc4d5f571952",
        "author": {
            "name": "Jarek Glowacki",
            "email": "jarekwg@gmail.com",
            "username": "jarekwg"
        },
        "committer": {
            "name": "Jarek Glowacki",
            "email": "jarekwg@gmail.com",
            "username": "jarekwg"
        },
        "added": [],
        "removed": [],
        "modified": ["apps/arafire-sandbox/deployment.yml"]
    },
    "repository": {
        "id": 139318783,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMzkzMTg3ODM=",
        "name": "uptick-cluster",
        "full_name": "uptick/uptick-cluster",
        "private": True,
        "owner": {
            "name": "uptick",
            "email": "hello@uptickhq.com",
            "login": "uptick",
            "id": 10147530,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwMTQ3NTMw",
            "avatar_url": "https://avatars1.githubusercontent.com/u/10147530?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/uptick",
            "html_url": "https://github.com/uptick",
            "followers_url": "https://api.github.com/users/uptick/followers",
            "following_url": "https://api.github.com/users/uptick/following{/other_user}",
            "gists_url": "https://api.github.com/users/uptick/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/uptick/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/uptick/subscriptions",
            "organizations_url": "https://api.github.com/users/uptick/orgs",
            "repos_url": "https://api.github.com/users/uptick/repos",
            "events_url": "https://api.github.com/users/uptick/events{/privacy}",
            "received_events_url": "https://api.github.com/users/uptick/received_events",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/uptick/uptick-cluster",
        "description": "Uptick Kubernetes cluster configuration.",
        "fork": False,
        "url": "https://github.com/uptick/uptick-cluster",
        "forks_url": "https://api.github.com/repos/uptick/uptick-cluster/forks",
        "keys_url": "https://api.github.com/repos/uptick/uptick-cluster/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/uptick/uptick-cluster/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/uptick/uptick-cluster/teams",
        "hooks_url": "https://api.github.com/repos/uptick/uptick-cluster/hooks",
        "issue_events_url": "https://api.github.com/repos/uptick/uptick-cluster/issues/events{/number}",
        "events_url": "https://api.github.com/repos/uptick/uptick-cluster/events",
        "assignees_url": "https://api.github.com/repos/uptick/uptick-cluster/assignees{/user}",
        "branches_url": "https://api.github.com/repos/uptick/uptick-cluster/branches{/branch}",
        "tags_url": "https://api.github.com/repos/uptick/uptick-cluster/tags",
        "blobs_url": "https://api.github.com/repos/uptick/uptick-cluster/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/uptick/uptick-cluster/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/uptick/uptick-cluster/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/uptick/uptick-cluster/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/uptick/uptick-cluster/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/uptick/uptick-cluster/languages",
        "stargazers_url": "https://api.github.com/repos/uptick/uptick-cluster/stargazers",
        "contributors_url": "https://api.github.com/repos/uptick/uptick-cluster/contributors",
        "subscribers_url": "https://api.github.com/repos/uptick/uptick-cluster/subscribers",
        "subscription_url": "https://api.github.com/repos/uptick/uptick-cluster/subscription",
        "commits_url": "https://api.github.com/repos/uptick/uptick-cluster/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/uptick/uptick-cluster/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/uptick/uptick-cluster/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/uptick/uptick-cluster/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/uptick/uptick-cluster/contents/{+path}",
        "compare_url": "https://api.github.com/repos/uptick/uptick-cluster/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/uptick/uptick-cluster/merges",
        "archive_url": "https://api.github.com/repos/uptick/uptick-cluster/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/uptick/uptick-cluster/downloads",
        "issues_url": "https://api.github.com/repos/uptick/uptick-cluster/issues{/number}",
        "pulls_url": "https://api.github.com/repos/uptick/uptick-cluster/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/uptick/uptick-cluster/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/uptick/uptick-cluster/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/uptick/uptick-cluster/labels{/name}",
        "releases_url": "https://api.github.com/repos/uptick/uptick-cluster/releases{/id}",
        "deployments_url": "https://api.github.com/repos/uptick/uptick-cluster/deployments",
        "created_at": 1530439884,
        "updated_at": "2019-07-18T05:05:03Z",
        "pushed_at": 1563426464,
        "git_url": "git://github.com/uptick/uptick-cluster.git",
        "ssh_url": "git@github.com:uptick/uptick-cluster.git",
        "clone_url": "https://github.com/uptick/uptick-cluster.git",
        "svn_url": "https://github.com/uptick/uptick-cluster",
        "homepage": "",
        "size": 2917,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 5,
        "license": None,
        "forks": 0,
        "open_issues": 5,
        "watchers": 0,
        "default_branch": "master",
        "stargazers": 0,
        "master_branch": "master",
        "organization": "uptick"
    },
    "pusher": {
        "name": "jarekwg",
        "email": "jarekwg@gmail.com"
    },
    "organization": {
        "login": "uptick",
        "id": 10147530,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwMTQ3NTMw",
        "url": "https://api.github.com/orgs/uptick",
        "repos_url": "https://api.github.com/orgs/uptick/repos",
        "events_url": "https://api.github.com/orgs/uptick/events",
        "hooks_url": "https://api.github.com/orgs/uptick/hooks",
        "issues_url": "https://api.github.com/orgs/uptick/issues",
        "members_url": "https://api.github.com/orgs/uptick/members{/member}",
        "public_members_url": "https://api.github.com/orgs/uptick/public_members{/member}",
        "avatar_url": "https://avatars1.githubusercontent.com/u/10147530?v=4",
        "description": ""
    },
    "sender": {
        "login": "jarekwg",
        "id": 5036488,
        "node_id": "MDQ6VXNlcjUwMzY0ODg=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5036488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jarekwg",
        "html_url": "https://github.com/jarekwg",
        "followers_url": "https://api.github.com/users/jarekwg/followers",
        "following_url": "https://api.github.com/users/jarekwg/following{/other_user}",
        "gists_url": "https://api.github.com/users/jarekwg/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jarekwg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jarekwg/subscriptions",
        "organizations_url": "https://api.github.com/users/jarekwg/orgs",
        "repos_url": "https://api.github.com/users/jarekwg/repos",
        "events_url": "https://api.github.com/users/jarekwg/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jarekwg/received_events",
        "type": "User",
        "site_admin": False
    }
}
